PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>

INSERT {
  ?taxon dwc:kingdom ?kingdom .
} WHERE {
  ?taxon dwc:taxonRank "kingdom" ;
         dwc:scientificName ?full_name .
  OPTIONAL { ?taxon dwc:scientificNameAuthorship ?authority . }
  BIND(REPLACE(?full_name, CONCAT(" ", COALESCE(?authority, ""), "$"), "") AS ?kingdom)
  # In some cases (8 of 23), the kingdom has an authority. the above should trim it.
}

INSERT {
  ?taxon dwc:kingdom ?kingdom .
} WHERE {
  ?taxon dwc:acceptedName?/dwc:parent*/dwc:kingdom ?kingdom .
}
