name: col

on: workflow_dispatch 

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      JENA_VERSION: 5.4.0

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Install dependencies
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install --no-install-recommends wget ca-certificates
          wget -q https://github.com/tarql/tarql/releases/download/v1.2/tarql-1.2.tar.gz -O /tmp/tarql-1.2.tar.gz || { echo "Failed to download Tarql"; exit 1; }
          cd /usr/local/lib/ && sudo tar xzf /tmp/tarql-1.2.tar.gz && rm /tmp/tarql-1.2.tar.gz
          sudo chmod a+x /usr/local/lib/tarql-1.2/bin/tarql
          sudo ln -s /usr/local/lib/tarql-1.2/bin/tarql /usr/local/bin/
          wget -qO /tmp/jena.tar.gz https://dlcdn.apache.org/jena/binaries/apache-jena-${JENA_VERSION}.tar.gz || { echo "Failed to download Jena"; exit 1; }
          sudo mkdir -p /opt/jena
          sudo tar xzf /tmp/jena.tar.gz -C /opt/jena --strip-components=1 || { echo "Failed to extract Jena"; exit 1; }
          rm /tmp/jena.tar.gz
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          
      - name: Get and convert
        run: |
          wget -q "https://api.checklistbank.org/dataset/3LR/export.zip?format=DwCA&extended=true" -O dwca.zip
          unzip dwca.zip Taxon.tsv
          tarql --ntriples --tabs query.sparql Taxon.tsv > col.nt
          
          export PATH="/opt/jena/bin:${PATH}"
          
          /opt/jena/bin/tdb2.tdbloader --loc=./tdbstore col.ttl
          /opt/jena/bin/tdb2.tdbupdate --loc=./tdbstore --update=add-kingdoms.sparql

          /opt/jena/bin/tdb2.tdbdump --loc=./tdbstore | > col.nt

          gzip -k col.nt
  
      # Using `tarql --ntriples` to emit ntriples directly.
      # This is a workaround to our lindas-upload-cronjob failing to convert a ttl file this large using rapper.
      # (It fails with an inexplicable `unexpected $end` in the middle of the file)
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/col.nt.gz
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
